---
# Ruby app enviroment preparation

- name: "Install dependecies for ruby and rbenv"
  ansible.builtin.yum:
    name:
      - git-core
      - zlib
      - zlib-devel
      - gcc-c++
      - patch
      - readline
      - readline-devel
      - libyaml-devel
      - libffi-devel
      - openssl-devel
      - make
      - bzip2
      - autoconf
      - automake
      - libtool
      - bison
      - curl
      - sqlite-devel
      - kernel-devel
      - libxml2-devel
      - libxslt-devel
      - libpq5-devel
    state: latest
    update_cache: true

- name: "Copy app project ruby"
  ansible.builtin.copy:
    src: /home/renearroi/devops/ansible/ansible_task/ruby/files/xpaste_practicum
    dest: /home/{{ ansible_user }}/.rbenv/app
    owner: vagrant
    group: vagrant
    mode: 0644
    
- name: "Clone rbenv from github"
  ansible.builtin.git:
    repo: 'https://github.com/rbenv/rbenv.git'
    dest: /home/{{ ansible_user }}/.rbenv
  become_user: "{{ ansible_user }}"

- name: "Add lines for lunch and install rbenv"
  blockinfile:
    path: "/home/{{ ansible_user }}/.bashrc"
    insertafter: "# User specific aliases and functions"
    block: |
        export PATH="$HOME/.rbenv/bin:$PATH"
        eval "$(rbenv init -)"
        export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"
  
- name: "Clone ruby from github"
  ansible.builtin.git:
    repo: 'https://github.com/rbenv/ruby-build.git'
    dest: /home/{{ ansible_user }}/.rbenv/plugins/ruby-build
  become_user: "{{ ansible_user }}"

- name: "Reload .bash_profile"
  ansible.builtin.shell:
    cmd: source /home/{{ ansible_user }}/.bashrc
  become_user: "{{ ansible_user }}"

- name: "Ensure ruby app exitst"
  stat:
    path: "/home/{{ ansible_user }}/.rbenv/versions/2.7.6"
  register: ruby_dir
    
- name: "Install ruby v 2.7.6"
  ansible.builtin.shell:
    cmd: /home/{{ ansible_user }}/.rbenv/bin/rbenv install -v 2.7.6
  become_user: "{{ ansible_user }}"
  when: not ruby_dir.stat.exists

- name: "Set ruby v 2.7.6 by global"
  ansible.builtin.shell:
    cmd: /home/{{ ansible_user }}/.rbenv/bin/rbenv global 2.7.6
  become_user: "{{ ansible_user }}"

- name: "Install bundle"
  community.general.gem:
    name: bundle
    state: latest 
    executable: /home/{{ ansible_user }}/.rbenv/shims/gem

- name: "Install bundle v 1.16.2"
  community.general.gem:
    name: bundle
    version: 1.16.2
    executable: /home/{{ ansible_user }}/.rbenv/shims/gem

- name: "Bundle preparations 1 step config build option"
  ansible.builtin.shell:
    cmd: /home/{{ ansible_user }}/.rbenv/shims/bundle config build.nokogiri --use-system-libraries
  become_user: "{{ ansible_user }}"

- name: "Bundle preparations 2 step config set option clean"
  ansible.builtin.shell:
    cmd: /home/{{ ansible_user }}/.rbenv/shims/bundle config set clean 'true'
  become_user: "{{ ansible_user }}"

- name: "Bundle preparations 3 step config set option no-cache"
  ansible.builtin.shell:
    cmd: /home/{{ ansible_user }}/.rbenv/shims/bundle config set no-cache 'true'
  become_user: "{{ ansible_user }}"

- name: "Bundle preparations 4 step config set option without development"
  ansible.builtin.shell:
    cmd: /home/{{ ansible_user }}/.rbenv/shims/bundle config set without 'development'
  become_user: "{{ ansible_user }}"

- name: "Bundle preparations 5 step install"
  ansible.builtin.bundler:
    executable: /home/{{ ansible_user }}/.rbenv/shims/bundle
    chdir: /home/{{ ansible_user }}/.rbenv/app/xpaste_practicum
  become_user: "{{ ansible_user }}"

- name: "Set systemd unit ruby"
  ansible.builtin.template:
    src: service.service.j2
    dest: /etc/systemd/system/{{app_name}}.service


    









    





                    

